### ISSUE TITLE
Android 13 Having issue using this package

### ISSUE THREAD

**Issue by KishanD24** [cj123195/multi_image_picker_plus#1]
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: The user has cancelled the selection
E/flutter ( 6760): #0      MethodChannelMultiImagePicker.pickImages (package:multi_image_picker_plus/multi_image_picker_plus_method_channel.dart:48)
E/flutter ( 6760): <asynchronous suspension>
E/flutter ( 6760): #1      addContainerState.selectImage (package:*****/****.dart:659)
E/flutter ( 6760): <asynchronous suspension>

**Comment by cj123195** [comment]
#2 look
