### ISSUE TITLE
Unable to Build with Target SDK 34

### ISSUE THREAD

**Issue by creativebymonarch** [cj123195/multi_image_picker_plus#10]
Hi,

The problem is : 
```
A problem occurred configuring project ':multi_image_picker_plus'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file: ../multi_image_picker_plus-0.0.4/android/build.gradle. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.
```

For Android Target SDK 34 (which Google requires to be updated by the end of August), the module doesn't have a namespace.

Here's an example if you need it: https://github.com/fluttercommunity/plus_plugins/blob/main/packages/android_intent_plus/android/build.gradle#L27

Thank you !

**Comment by cj123195** [comment]
Fixed in v0.0.5.

**Comment by creativebymonarch** [comment]
Thank you for your changes.

As also mentioned during the build, Android requires the 'package' attribute to be removed from the Manifest like this :

```
From this :
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.tianxin.multi_image_picker_plus">
</manifest>

To this :
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
</manifest>
```

But I'm not sure if this could impact other SDK versions.

**Comment by cj123195** [comment]
I did not encounter such issues during my local testing build. I think your situation is just an isolated case. I am not good at Android development, so I cannot be sure if it will affect other versions of the SDK.
