### ISSUE TITLE
Camera is not working

### ISSUE THREAD

**Issue by ZeyadHessien-Dev** [cj123195/multi_image_picker_plus#11]
hasCameraInPickerPage: true,
camera isn't working for any platform, I don't know why but I already added all permissions

**Comment by cj123195** [comment]
I did not reproduce your problem. I don't know if you have found the correct position for the camera display. The camera is not displayed on the album page, but on the photo page.
![Screenshot_20240828_090858_com tianxin multi_image_picker_plus_example](https://github.com/user-attachments/assets/d2023db0-d505-422d-b12c-068326b94a17)
