### ISSUE TITLE
picked image has greater than the actual size

### ISSUE THREAD

**Issue by BunnyBuddy** [cj123195/multi_image_picker_plus#13]
On iOS, almost every image we pick has a different size than the actual size shown in the gallery. On Android its reducing the size

For example:
An image of 5 mb is showing 7 mb and similarly an image of 8.3 mb is showing 10 mb.

can this be adjusted somehow ? 
it could be due to the compression being applied to the image by its native image picker.

**Comment by cj123195** [comment]
Due to some objective factors, I am temporarily unable to handle the iOS issue. You can check the [BSImagePicker](https://github.com/mikaoj/BSImagePicker) repository for a solution.
