### ISSUE TITLE
Can't pick multiple images on Android

### ISSUE THREAD

**Issue by BunnyBuddy** [cj123195/multi_image_picker_plus#6]
I am trying to pick multiple images on android, with one image its okay but a weird issue is happens when I pick more than 1 image.
Images are picked okay but as soon as I finalise them,
I get error 

PlatformException(already_active, Image picker is already active, null, null)

Can you please check what's the issue here

**Comment by BunnyBuddy** [comment]
Okay I've narrowed it down to the issue, the problem is when I try to convert Asset to File it breaks the code for multiple images, only works for the first one.

**Comment by cj123195** [comment]
> Okay I've narrowed it down to the issue, the problem is when I try to convert Asset to File it breaks the code for multiple images, only works for the first one.

Due to work reasons, I may not be able to troubleshoot this issue in a timely manner, but I will do it when I have time. If you have fixed this issue, you can submit a merge request.

**Comment by cj123195** [comment]
I have reproduced this issue and fixed it. You can give it a try.
