### ISSUE TITLE
Camera Access

### ISSUE THREAD

**Issue by sjordan2010** [cj123195/multi_image_picker_plus#7]
I'm having trouble figuring out how to access the camera while picking images.

In the original example there was an enableCamera property, but that doesn't seem to an option now.

I found hasCameraInPickerPage within AndroidOptions, but nothing for iosOptions yet.

**Comment by cj123195** [comment]
Replace enableCamera with hasCameraInPickerPage.

**Comment by sjordan2010** [comment]
<img width="476" alt="Screenshot 2024-03-07 at 4 17 54 PM" src="https://github.com/cj123195/multi_image_picker_plus/assets/102764377/7d8fa79f-30e9-4de1-a35b-4c770612f7b1">


error:
The named parameter 'hasCameraInPickerPage' isn't defined.
Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'hasCameraInPickerPage'.dart[undefined_named_parameter](https://dart.dev/diagnostics/undefined_named_parameter)

**Comment by cj123195** [comment]
The IOS side uses the BSImagePicker plugin, which has removed the setting that allows the use of cameras in its latest version. If you want to use this setting, you can fork a version and replace it with the old version.
