### ISSUE TITLE
Android image Empty

### ISSUE THREAD

**Issue by thisadee2897** [cj123195/multi_image_picker_plus#8]
resultList = await MultiImagePicker.pickImages(
        selectedAssets: images,
        iosOptions: IOSOptions(
          doneButton:
              UIBarButtonItem(title: 'ยืนยัน', tintColor: colorScheme.primary),
          cancelButton:
              UIBarButtonItem(title: 'ยกเลิก', tintColor: colorScheme.primary),
          albumButtonColor: colorScheme.primary,
          settings: iosSettings,
        ),
        androidOptions: AndroidOptions(
          maxImages:5,
          actionBarColor: colorScheme.surface,
          actionBarTitleColor: colorScheme.onSurface,
          statusBarColor: colorScheme.surface,
          actionBarTitle: "ยืนยัน",
          allViewTitle: "All Photos",
          useDetailsView: true,
          selectCircleStrokeColor: colorScheme.primary,
          exceptMimeType: {MimeType.PNG, MimeType.JPEG},
        ),
      );
![Screenshot 2567-02-20 at 11 04 32](https://github.com/cj123195/multi_image_picker_plus/assets/69580511/f6975f9b-2ff4-4295-aae2-06411e12d726)

**Comment by cj123195** [comment]
I have not reproduced this issue. Can you confirm if there are any photos in the album?

**Comment by thisadee2897** [comment]
ok I'm chang to exceptMimeType: {MimeType.PNG}
