### ISSUE TITLE
Video Selection Functionality Not Available

### ISSUE THREAD

**Issue by Joao-VictorF** [cj123195/multi_image_picker_plus#9]
Hi there,

I noticed that the README mentions the ability to pick videos, and there's even a video demo showing this functionality. However, after reviewing the documentation and experimenting with the library, I can't find a way to actually select videos using this package.

Could you provide guidance on how to enable this feature, or confirm whether video selection is currently supported?

Thanks for your help and for the great work on this library!

**Comment by cj123195** [comment]
Video selection is only available on iOS and you can use it by set supportedMediaTypes of AssetsSettings like following code:
```dart
const AssetsSetting assetsSetting = AssetsSetting(
      // Set to allow pick videos.
      supportedMediaTypes: {MediaTypes.video, MediaTypes.image},
    );
    final CupertinoSettings iosSettings = CupertinoSettings(
      fetch: const FetchSetting(album: albumSetting, assets: assetsSetting),
      theme: themeSetting,
      selection: selectionSetting,
      dismiss: dismissSetting,
      list: listSetting,
    );
```

This library is only based on the Flutter wrapper of Android FishBun and iOS BSImagePicker. For detailed configuration, please refer to [FishBun](https://github.com/sangcomz/FishBun) and [BSImagePicker](https://github.com/mikaoj/BSImagePicker).
